#!/bin/sh

cd drupal
PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
	oIFS=$IFS
	IFS='
	'
	SFILES="$1"
	IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Checking PHP Lint..."
for FILE in $SFILES
do
	php -l -d display_errors=0 $PROJECT/$FILE
	if [ $? != 0 ]
	then
		echo "Fix the error before commit."
		exit 1
	fi
	FILES="$FILES $PROJECT/$FILE"
done

if [ "$FILES" != "" ]
then
	echo "Running Code Sniffer..."
	vendor/bin/phpcs --standard=vendor/drupal/coder/coder_sniffer/Drupal,vendor/drupal/coder/coder_sniffer/PSR1,vendor/drupal/coder/coder_sniffer/DrupalPractice --colors --report=checkstyle --report-file="logs/phpcs.xml" --encoding=utf-8 -n -p $FILES
	if [ $? != 0 ]
	then
	  echo "Trying to automatically fix errors by phpcbf."
	  vendor/bin/phpcbf --standard=vendor/drupal/coder/coder_sniffer/Drupal,vendor/drupal/coder/coder_sniffer/PSR1,vendor/drupal/coder/coder_sniffer/DrupalPractice --extensions='php,module,inc,install,test,profile,theme,css,info,txt,md' $FILES
	  echo "Running PhpStan Drupal analysis."
	  vendor/bin/phpstan analyse -l 4 -c phpstan.neon $FILES
		echo "Plz fix error(s) before commit."
		exit 1
	fi
fi

exit $?